// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb1cj9TJEAGq_apLYQMRSTFfWiUmrwUnU',
    appId: '1:1010432961609:web:d359ff0c2bb5bf66f36398',
    messagingSenderId: '1010432961609',
    projectId: 'demo2-d0415',
    authDomain: 'demo2-d0415.firebaseapp.com',
    storageBucket: 'demo2-d0415.appspot.com',
    measurementId: 'G-N7N06RFXR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVpbom2bG366K69Klzhk6IImN0IjVJSt0',
    appId: '1:1010432961609:android:fdcefaec58cef00af36398',
    messagingSenderId: '1010432961609',
    projectId: 'demo2-d0415',
    storageBucket: 'demo2-d0415.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7tcN6CcHNHaKmeBuBIXssJCH-UKSlzXY',
    appId: '1:1010432961609:ios:fd83ca5c5579d38af36398',
    messagingSenderId: '1010432961609',
    projectId: 'demo2-d0415',
    storageBucket: 'demo2-d0415.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
